### ISSUE TITLE
Mathematical notation and learn math in general

### ISSUE THREAD

**Issue by nelson-brochado** [rossant/awesome-math#10]
Hi,

I'm not sure if this awesome points to some articles regarding _learning mathematics_ (in general) and _mathematics language and notation_. 

It would be nice also to have something regarding the topic. If you're interested I've created a [Github's repository about "mathematical language and notation"](https://github.com/nelson-brochado/mathematical-language).

**Comment by nelson-brochado** [comment]
@rossant Ok, here you have the repository:

> [https://github.com/nelson-brochado/mathematical-notation](https://github.com/nelson-brochado/mathematical-notation)

**Comment by rossant** [comment]
sounds good! feel free to propose a PR with a brand new section about notations

**Comment by nelson-brochado** [comment]
@rossant I've changed the direction of the repository a little though. Now it's called "understanding-math", and includes a section for "mathematical language" and "mathematical notation". I'm not sure if this is a good idea, but ideas are welcome.

**Comment by rossant** [comment]
ok! you can also make a PR with just a link to your repo
