### ISSUE TITLE
Suggestions on Trigonometry and Algebra

### ISSUE THREAD

**Issue by shahinism** [rossant/awesome-math#21]
I suggest the following books deserve to be on this list:
- [Beginning and Intermediate Algebra](http://www.wallace.ccfaculty.org/book/Beginning_and_Intermediate_Algebra.pdf) By Tyler Wallace
- [Trignometry](http://www.mecmath.net/trig/trigbook.pdf) By Michael Corral

They are both well written, original and free resources. 

Thank you for collecting this great list.

**Comment by rossant** [comment]
Good idea, feel free to propose a pull request! :+1:

**Comment by shahinism** [comment]
Done.
