### ISSUE TITLE
Please use the official link to my Linear Algebra

### ISSUE THREAD

**Issue by jimhefferon** [rossant/awesome-math#25]
Hi,  Thanks for promoting open texts.  Please change your link to my Linear Algebra.  

    Jim Hefferon Linear Algebra

to: 
  
    http://joshua.smcvt.edu/linearalgebra

This link has a number of advantages.  One is that it gets a person the current book version (the version you point to is *very* old).  Another is that the link also gives the solutions manual, containing worked answers to every problem.  It also gives slides for classroom use, and a computer lab manual for use with Sage.

Thanks, Jim

**Comment by rossant** [comment]
Done, thanks for letting me know!
