### ISSUE TITLE
Long list of math texts

### ISSUE THREAD

**Issue by ligurio** [rossant/awesome-math#26]
There is a list with math texts online - http://people.math.gatech.edu/~cain/textbooks/onlinebooks.html.
I think it would be nice to add links to these texts to the awesome-math.
Sorry, I don't have time to prepare a patch and make a pull request.

**Comment by mdave16** [comment]
Did you want someone to add the books one by one or just that link itself?

**Comment by ligurio** [comment]
I believe one by one would be better.

**Comment by rossant** [comment]
should be done
