### ISSUE TITLE
Numerous Dead links

### ISSUE THREAD

**Issue by neo4reo** [rossant/awesome-math#75]
_Hi Cyrille,
Thanks for the great work putting this togethor.
I just noticed that many of the links to individual resources are now dead and need updating or replacing.
Regards._

**Comment by rossant** [comment]
Please feel free to point out any specific dead links you may have found, together with a replacement link if you find them.

**Comment by KipHamiltons** [comment]
Elementary number theory by burton is a dead link

**Comment by simonescu** [comment]
Linear Algebra by Peter Petersen is a dead link.
Linear Algebra by Jim Hefferon was entered twice in the Linear Algebra section.
