### ISSUE TITLE
Referencing related awesome lists

### ISSUE THREAD

**Issue by mostafatouny** [rossant/awesome-math#91]
Hello,
I wish to add couple of **open-accessed** resources for _machine learning theory_. However this list seems to better focused on pure math subjects like analysis, linear algebra, set theory, ..etc rather than ones which are motivated by other areas like computer science or engineering.

I wonder whether it is possible if I added a section for _related awesome lists_ and included [theoretical CS](https://github.com/mostafatouny/awesome-theoretical-computer-science). You might like to remove Mathematics for Computer Science_ section after I move all of its resources into _theoretical CS_ list

By the way, I had contributed to _awesome-math_ list multiple times; I do not intend to spam. Please let me know your genuine feedback. Don't feel reluctant not to express your rejection. Let me know if you have better ideas also.

**Comment by rossant** [comment]
- Good idea to add a "related awesome lists" section
- No problem to add open-access resources for ML, for example there's already a Statistical Learning section
- I think it's fine to keep existing sections such as Mathematics for Computer Science, and pointing to more complete awesome lists
- Thank you for your contributions!
